title: my pyramid
description: i wann pyramid
template:
  repo: my-pyramid-template
  name: my-pyramid
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
